# Generated by Django 4.2.16 on 2026-09-21 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgrCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iuspt_card', models.CharField(max_length=255)),
                ('directum_card', models.IntegerField()),
                ('cr_ed', models.CharField(max_length=255)),
                ('iuspt_card_2', models.CharField(max_length=255)),
                ('card_date', models.CharField(max_length=255)),
                ('hist_id', models.CharField(max_length=255)),
                ('vendor_card', models.CharField(max_length=255)),
                ('card_title', models.CharField(max_length=255)),
                ('iuspt_vendor', models.CharField(max_length=255)),
                ('card_kurator', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
