# Generated by Django 4.2.16 on 2026-09-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EdoVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
                ('kpp', models.CharField(max_length=9, verbose_name='КПП')),
                ('fns_id', models.CharField(max_length=64, verbose_name='ФНС ИД')),
                ('vendor', models.CharField(max_length=255, verbose_name='Код кредитора в ИУС П Т')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Контрагент ЭДО',
                'verbose_name_plural': 'Контрагенты ЭДО',
                'ordering': ['-updated_at'],
            },
        ),
    ]
