# Generated by Django 4.2.16 on 2026-09-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soap_app', '0004_edovendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soaptransaction',
            name='request_data',
            field=models.JSONField(default=dict, verbose_name='Данные запроса'),
        ),
    ]
